#@HDR@	$Id$
#@HDR@		Copyright 2024 by
#@HDR@		Christopher Caldwell/Brightsands
#@HDR@		P.O. Box 401, Bailey Island, ME 04003
#@HDR@		All Rights Reserved
#@HDR@
#@HDR@	This software comprises unpublished confidential information
#@HDR@	of Brightsands and may not be used, copied or made available
#@HDR@	to anyone, except in accordance with the license under which
#@HDR@	it is furnished.
@VAR_LIST =
    (
    {name=>"Language",
	prompt=>	{ en=>"What language are you most fluent in?" },
	noptions=>	1,
	options=>	[
			{code=>"en", "en"=>"English", "en"=>"English"},
			{code=>"af", "en"=>"Afrikaans", "af"=>"Afrikaans"},
			{code=>"sq", "en"=>"Albanian", "sq"=>"Shqip"},
			{code=>"am", "en"=>"Amharic", "am"=>"አማርኛ"},
			{code=>"ar", "en"=>"Arabic", "ar"=>"ﺔﻴﺑﺮﻌﻟﺍ"},
			{code=>"hy", "en"=>"Armenian", "hy"=>"Հայերեն"},
			{code=>"as", "en"=>"Assamese", "as"=>"অসমীয়া"},
			{code=>"ay", "en"=>"Aymara", "ay"=>"Aymar aru"},
			{code=>"az", "en"=>"Azerbaijani", "az"=>"Azərbaycanca"},
			{code=>"bm", "en"=>"Bambara", "bm"=>"Bamanankan"},
			{code=>"ba", "en"=>"Bashkir", "ba"=>"Башҡортса"},
			{code=>"eu", "en"=>"Basque", "eu"=>"Euskara"},
			{code=>"be", "en"=>"Belarusian", "be"=>"беларуская"},
			{code=>"bn", "en"=>"Bengali", "bn"=>"বাংলা"},
			{code=>"bho", "en"=>"Bhojpuri", "bho"=>"भोजपुरी"},
			{code=>"bs", "en"=>"Bosnian", "bs"=>"Bosanski"},
			{code=>"bg", "en"=>"Bulgarian", "bg"=>"български"},
			{code=>"yue", "en"=>"Cantonese", "yue"=>"粵語"},
			{code=>"ca", "en"=>"Catalan", "ca"=>"Català"},
			{code=>"ceb", "en"=>"Cebuano", "ceb"=>"Cebuano"},
			{code=>"ny", "en"=>"Chichewa", "ny"=>"Nyanja"},
			{code=>"lzh", "en"=>"Chinese (Literary)", "lzh"=>"文言"},
			{code=>"zh-CN", "en"=>"Chinese (Simplified)", "zh-CN"=>"简体中文"},
			{code=>"zh-TW", "en"=>"Chinese (Traditional)", "zh-TW"=>"繁體中文"},
			{code=>"cv", "en"=>"Chuvash", "cv"=>"Чӑвашла"},
			{code=>"co", "en"=>"Corsican", "co"=>"Corsu"},
			{code=>"hr", "en"=>"Croatian", "hr"=>"Hrvatski"},
			{code=>"cs", "en"=>"Czech", "cs"=>"Čeština"},
			{code=>"da", "en"=>"Danish", "da"=>"Dansk"},
			{code=>"prs", "en"=>"Dari", "prs"=>"ﯼﺭﺩ"},
			{code=>"dv", "en"=>"Dhivehi", "dv"=>"ހިވެދި"},
			{code=>"doi", "en"=>"Dogri", "doi"=>"डोगरी"},
			{code=>"nl", "en"=>"Dutch", "nl"=>"Nederlands"},
			{code=>"mhr", "en"=>"Eastern Mari", "mhr"=>"Олык марий"},
			{code=>"eo", "en"=>"Esperanto", "eo"=>"Esperanto"},
			{code=>"et", "en"=>"Estonian", "et"=>"Eesti"},
			{code=>"ee", "en"=>"Ewe", "ee"=>"Eʋegbe"},
			{code=>"fo", "en"=>"Faroese", "fo"=>"Føroyskt"},
			{code=>"fj", "en"=>"Fijian", "fj"=>"Vosa Vakaviti"},
			{code=>"tl", "en"=>"Filipino", "tl"=>"Filipino"},
			{code=>"fi", "en"=>"Finnish", "fi"=>"Suomi"},
			{code=>"fr", "en"=>"French", "fr"=>"Français"},
			{code=>"fr-CA", "en"=>"French (Canadian)", "fr-CA"=>"Français canadien"},
			{code=>"fy", "en"=>"Frisian", "fy"=>"Frysk"},
			{code=>"gl", "en"=>"Galician", "gl"=>"Galego"},
			{code=>"ka", "en"=>"Georgian", "ka"=>"ქართული"},
			{code=>"de", "en"=>"German", "de"=>"Deutsch"},
			{code=>"el", "en"=>"Greek", "el"=>"Ελληνικά"},
			{code=>"gn", "en"=>"Guarani", "gn"=>"Avañe'ẽ"},
			{code=>"gu", "en"=>"Gujarati", "gu"=>"ગુજરાતી"},
			{code=>"ht", "en"=>"Haitian Creole", "ht"=>"Kreyòl Ayisyen"},
			{code=>"ha", "en"=>"Hausa", "ha"=>"Hausa"},
			{code=>"haw", "en"=>"Hawaiian", "haw"=>"ʻŌlelo Hawaiʻi"},
			{code=>"he", "en"=>"Hebrew", "he"=>"תירִבְעִ"},
			{code=>"mrj", "en"=>"Hill Mari", "mrj"=>"Кырык мары"},
			{code=>"hi", "en"=>"Hindi", "hi"=>"हिन्दी"},
			{code=>"hmn", "en"=>"Hmong", "hmn"=>"Hmoob"},
			{code=>"hu", "en"=>"Hungarian", "hu"=>"Magyar"},
			{code=>"is", "en"=>"Icelandic", "is"=>"Íslenska"},
			{code=>"ig", "en"=>"Igbo", "ig"=>"Igbo"},
			{code=>"ilo", "en"=>"Ilocano", "ilo"=>"Ilokano"},
			{code=>"id", "en"=>"Indonesian", "id"=>"Bahasa Indonesia"},
			{code=>"ikt", "en"=>"Inuinnaqtun", "ikt"=>"Inuinnaqtun"},
			{code=>"iu", "en"=>"Inuktitut", "iu"=>"ᐃᓄᒃᑎᑐᑦ"},
			{code=>"iu-Latn", "en"=>"Inuktitut (Latin)", "iu-Latn"=>"Inuktitut"},
			{code=>"ga", "en"=>"Irish", "ga"=>"Gaeilge"},
			{code=>"it", "en"=>"Italian", "it"=>"Italiano"},
			{code=>"ja", "en"=>"Japanese", "ja"=>"日本語"},
			{code=>"jv", "en"=>"Javanese", "jv"=>"Basa Jawa"},
			{code=>"kn", "en"=>"Kannada", "kn"=>"ಕನ್ನಡ"},
			{code=>"kk", "en"=>"Kazakh", "kk"=>"Қазақ тілі"},
			{code=>"km", "en"=>"Khmer", "km"=>"ភាសាខ្មែរ"},
			{code=>"rw", "en"=>"Kinyarwanda", "rw"=>"Ikinyarwanda"},
			{code=>"tlh-Latn", "en"=>"Klingon", "tlh-Latn"=>"tlhIngan Hol"},
			{code=>"gom", "en"=>"Konkani", "gom"=>"कोंकणी"},
			{code=>"ko", "en"=>"Korean", "ko"=>"한국어"},
			{code=>"kri", "en"=>"Krio", "kri"=>"Krio"},
			{code=>"ckb", "en"=>"Kurdish (Central)", "ckb"=>"ﯽﻧﺍﺭﯚﺳ"},
			{code=>"ku", "en"=>"Kurdish (Northern)", "ku"=>"Kurmancî"},
			{code=>"ky", "en"=>"Kyrgyz", "ky"=>"Кыргызча"},
			{code=>"lo", "en"=>"Lao", "lo"=>"ລາວ"},
			{code=>"la", "en"=>"Latin", "la"=>"Latina"},
			{code=>"lv", "en"=>"Latvian", "lv"=>"Latviešu"},
			{code=>"ln", "en"=>"Lingala", "ln"=>"Lingála"},
			{code=>"lt", "en"=>"Lithuanian", "lt"=>"Lietuvių"},
			{code=>"lg", "en"=>"Luganda", "lg"=>"Luganda"},
			{code=>"lb", "en"=>"Luxembourgish", "lb"=>"Lëtzebuergesch"},
			{code=>"mk", "en"=>"Macedonian", "mk"=>"Македонски"},
			{code=>"mai", "en"=>"Maithili", "mai"=>"मैथिली"},
			{code=>"mg", "en"=>"Malagasy", "mg"=>"Malagasy"},
			{code=>"ms", "en"=>"Malay", "ms"=>"Bahasa Melayu"},
			{code=>"ml", "en"=>"Malayalam", "ml"=>"മലയാളം"},
			{code=>"mt", "en"=>"Maltese", "mt"=>"Malti"},
			{code=>"mi", "en"=>"Maori", "mi"=>"Māori"},
			{code=>"mr", "en"=>"Marathi", "mr"=>"मराठी"},
			{code=>"mni-Mtei", "en"=>"Meiteilon", "mni-Mtei"=>"ꯃꯤꯇꯩꯂꯣꯟ"},
			{code=>"lus", "en"=>"Mizo", "lus"=>"Mizo ṭawng"},
			{code=>"mn", "en"=>"Mongolian", "mn"=>"Монгол"},
			{code=>"mn-Mong", "en"=>"Mongolian (Traditional)", "mn-Mong"=>"ᠮᠣᠩᠭᠣᠯ"},
			{code=>"my", "en"=>"Myanmar", "my"=>"မြန်မာစာ"},
			{code=>"ne", "en"=>"Nepali", "ne"=>"नेपाली"},
			{code=>"no", "en"=>"Norwegian", "no"=>"Norsk"},
			{code=>"or", "en"=>"Odia", "or"=>"ଓଡ଼ିଆ"},
			{code=>"om", "en"=>"Oromo", "om"=>"Afaan Oromoo"},
			{code=>"pap", "en"=>"Papiamento", "pap"=>"Papiamentu"},
			{code=>"ps", "en"=>"Pashto", "ps"=>"ﻮﺘښﭘ"},
			{code=>"fa", "en"=>"Persian", "fa"=>"ﯽﺳﺭﺎﻓ"},
			{code=>"pl", "en"=>"Polish", "pl"=>"Polski"},
			{code=>"pt-BR", "en"=>"Portuguese (Brazilian)", "pt-BR"=>"Português Brasileiro"},
			{code=>"pt-PT", "en"=>"Portuguese (European)", "pt-PT"=>"Português Europeu"},
			{code=>"pa", "en"=>"Punjabi", "pa"=>"ਪੰਜਾਬੀ"},
			{code=>"qu", "en"=>"Quechua", "qu"=>"Runasimi"},
			{code=>"otq", "en"=>"Querétaro Otomi", "otq"=>"Hñąñho"},
			{code=>"ro", "en"=>"Romanian", "ro"=>"Română"},
			{code=>"ru", "en"=>"Russian", "ru"=>"Русский"},
			{code=>"sm", "en"=>"Samoan", "sm"=>"Gagana Sāmoa"},
			{code=>"sa", "en"=>"Sanskrit", "sa"=>"संस्कृतम्"},
			{code=>"gd", "en"=>"Scots Gaelic", "gd"=>"Gàidhlig"},
			{code=>"nso", "en"=>"Sepedi", "nso"=>"Sepedi"},
			{code=>"sr-Cyrl", "en"=>"Serbian (Cyrillic)", "sr-Cyrl"=>"Српски"},
			{code=>"sr-Latn", "en"=>"Serbian (Latin)", "sr-Latn"=>"Srpski"},
			{code=>"st", "en"=>"Sesotho", "st"=>"Sesotho"},
			{code=>"sn", "en"=>"Shona", "sn"=>"chiShona"},
			{code=>"sd", "en"=>"Sindhi", "sd"=>"ﻱﮅﻨﺳ"},
			{code=>"si", "en"=>"Sinhala", "si"=>"සිංහල"},
			{code=>"sk", "en"=>"Slovak", "sk"=>"Slovenčina"},
			{code=>"sl", "en"=>"Slovenian", "sl"=>"Slovenščina"},
			{code=>"so", "en"=>"Somali", "so"=>"Soomaali"},
			{code=>"es", "en"=>"Spanish", "es"=>"Español"},
			{code=>"su", "en"=>"Sundanese", "su"=>"Basa Sunda"},
			{code=>"sw", "en"=>"Swahili", "sw"=>"Kiswahili"},
			{code=>"sv", "en"=>"Swedish", "sv"=>"Svenska"},
			{code=>"ty", "en"=>"Tahitian", "ty"=>"Reo Tahiti"},
			{code=>"tg", "en"=>"Tajik", "tg"=>"Тоҷикӣ"},
			{code=>"ta", "en"=>"Tamil", "ta"=>"தமிழ்"},
			{code=>"tt", "en"=>"Tatar", "tt"=>"татарча"},
			{code=>"te", "en"=>"Telugu", "te"=>"తెలుగు"},
			{code=>"th", "en"=>"Thai", "th"=>"ไทย"},
			{code=>"bo", "en"=>"Tibetan", "bo"=>"བོད་ཡིག"},
			{code=>"ti", "en"=>"Tigrinya", "ti"=>"ትግርኛ"},
			{code=>"to", "en"=>"Tongan", "to"=>"Lea faka-Tonga"},
			{code=>"ts", "en"=>"Tsonga", "ts"=>"Xitsonga"},
			{code=>"tr", "en"=>"Turkish", "tr"=>"Türkçe"},
			{code=>"tk", "en"=>"Turkmen", "tk"=>"Türkmen"},
			{code=>"tw", "en"=>"Twi", "tw"=>"Twi"},
			{code=>"udm", "en"=>"Udmurt", "udm"=>"Удмурт"},
			{code=>"uk", "en"=>"Ukrainian", "uk"=>"Українська"},
			{code=>"hsb", "en"=>"Upper Sorbian", "hsb"=>"Hornjoserbšćina"},
			{code=>"ur", "en"=>"Urdu", "ur"=>"ﻭﺩُﺭﺍُ"},
			{code=>"ug", "en"=>"Uyghur", "ug"=>"ﻰﻠﯩﺗ ﺭﯘﻐﻳﯘﺋ"},
			{code=>"uz", "en"=>"Uzbek", "uz"=>"Oʻzbek tili"},
			{code=>"vi", "en"=>"Vietnamese", "vi"=>"Tiếng Việt"},
			{code=>"cy", "en"=>"Welsh", "cy"=>"Cymraeg"},
			{code=>"xh", "en"=>"Xhosa", "xh"=>"isiXhosa"},
			{code=>"sah", "en"=>"Yakut", "sah"=>"Sakha"},
			{code=>"yi", "en"=>"Yiddish", "yi"=>"שידיִי"},
			{code=>"yo", "en"=>"Yoruba", "yo"=>"Yorùbá"},
			{code=>"yua", "en"=>"Yucatec Maya", "yua"=>"Màaya T'àan"},
			{code=>"zu", "en"=>"Zulu", "zu"=>"isiZulu"}
			] },
    {name=>"Documents",
	prompt=>	{ en=>"What documents do you need to prepare?" },
	options=>	[
			{en=>"English Visa"},
			{en=>"French Visa"},
			] },
    {name=>"Vietnam_sponsor",
	    prompt=>	{ en=>"Who is sponsoring you in Vietnam?" },
	    cols=>	20 }
    );
1;
